-- 01_init_atlas_platform.sql
-- Create Atlas database and core schemas

CREATE DATABASE IF NOT EXISTS ATLAS_PLATFORM_DB;

USE DATABASE ATLAS_PLATFORM_DB;

CREATE SCHEMA IF NOT EXISTS ATLAS_FEATURE_STORE;
CREATE SCHEMA IF NOT EXISTS ATLAS_MODEL_REGISTRY;
CREATE SCHEMA IF NOT EXISTS ATLAS_MONITORING;
