-- 02_feature_store.sql
-- Customer transaction feature table

USE DATABASE ATLAS_PLATFORM_DB;
USE SCHEMA ATLAS_FEATURE_STORE;

CREATE OR REPLACE TABLE CUSTOMER_TX_FEATURES (
    CUSTOMER_ID         STRING,
    AS_OF_DATE          DATE,
    TX_30D_COUNT        NUMBER,
    TX_30D_AMOUNT       NUMBER(18,2),
    TX_30D_AVG_TICKET   NUMBER(18,2)
);

INSERT INTO CUSTOMER_TX_FEATURES
  (CUSTOMER_ID, AS_OF_DATE, TX_30D_COUNT, TX_30D_AMOUNT, TX_30D_AVG_TICKET)
VALUES
  ('CUST_001', CURRENT_DATE(), 12, 1200.00, 100.00),
  ('CUST_002', CURRENT_DATE(),  5,  250.00,  50.00),
  ('CUST_003', CURRENT_DATE(), 30, 6000.00, 200.00);

-- Preview
SELECT * FROM CUSTOMER_TX_FEATURES;
